codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        paths:
          - "internal/"
          - "pkg/"
    patch:
      default:
        target: 50%
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "test/"
  - "examples/"
  - "cmd/"
  - "**/*_test.go"
  - "**/mock_*.go"
  - "internal/storage/bitmap/"
  - "internal/storage/btree/"
  - "internal/storage/compression/"
  - "internal/parser/statement_clone.go"
  - "internal/btree/btree.go"
  - "internal/storage/binser/manager.go"
  - "internal/storage/binser/extensions.go"
  - "internal/storage/binser/statistics_metadata.go"
  - "internal/storage/binser/json_encoder.go"
  - "internal/sql/executor/streaming_join.go"
  - "internal/fastmap/int64_sync_map.go"
  - "internal/storage/mvcc/direct.go"
  - "internal/parser/sql_types.go"